### ISSUE TITLE
Co-simulation Orchestration Engine - Co-simulation Orchestration Engine version 1.0.1 and 1.0.0 not downloading

### ISSUE THREAD

**Issue by Quanalogy** [INTO-CPS-Association/into-cps-application#62] opened 2019-02-27 12:13 UTC
Using Fedora 29, java -version
openjdk version "1.8.0_201"
OpenJDK Runtime Environment (build 1.8.0_201-b09)
OpenJDK 64-Bit Server VM (build 25.201-b09, mixed mode)

Using the download manager and selecting release version 1.0.0 or 1.0.1 of "Co-simulation Orchestration Engine - Co-simulation Orchestration Engine" download results in 0% progress of the download after some time. Monitoring network it seems like it is not downloading anything, while when trying Release 0.0.25 it download instantly.

**Comment by CThuleHansen** [comment] 2019-02-27 17:14
I have fixed an issue in the json, could you try 1.0.1 again?
Which version of the into-cps app are you using?

**Comment by clegaard** [comment] 2019-05-06 08:07
Issue is present using:
windows 10
Into-cps-app 3.8.4
downloading coe from 1.0.1 or 1.0.0

As stated it works with 0.0.25.

There is no output in the developer terminal.
The file is visible in the explorer but is stuck at ~ 0 KB

I also know that this is a general problem experienced by several people in the system engineering course at AU.

I am willing to test with other version of the app if necessary, given that the issue is being worked on.

**Comment by CThuleHansen** [comment] 2019-05-06 11:00
I just checked, the link is dead currently.. Will fix

**Comment by CThuleHansen** [comment] 2019-05-06 11:37
Fixed in https://github.com/INTO-CPS-Association/INTO-CPS-Association.github.io/commit/2baf0f0cd4b396e976a8a682020dba5758b7df1c

**Closed by CThuleHansen** 2019-05-06 11:37 UTC
Labels: bug
